title: The Inked Quill
author: Shankar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The quilled thoughts of a soul in billions of others is posted here. 
  You are warned because this one soul can impact your souls just like the way it has impacted other souls.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
